name = "essay-grader-api"
main = "worker.js"
compatibility_date = "2026-07-22"

[vars]
NVIDIA_MODELS = "meta/llama-3.1-8b-instruct,nvidia/nvidia-nemotron-nano-9b-v2,openai/gpt-oss-20b,nvidia/nemotron-3-nano-30b-a3b,meta/llama-3.3-70b-instruct"